<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://www.dpworld.com/SOA_DPWORLD/I003_BorrarAsientoContable" xmlns:tns="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0"
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:ns3="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns4="commonj.sdo/xml"
                xmlns:ns5="commonj.sdo/java" xmlns:ns6="commonj.sdo"
                xmlns:ns2="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDL_SCA/BorrarAsientoContable.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BorrarACRequest" namespace="http://www.dpworld.com/SOA_DPWORLD/I003_BorrarAsientoContable"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ErpIntegrationService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="submitESSJobRequest" namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/types/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI NOV 09 04:34:50 ECT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:submitESSJobRequest>
         <tns:jobPackageName>
            <xsl:value-of select="/ns0:BorrarACRequest/ns0:jobPackageName"/>
         </tns:jobPackageName>
         <tns:jobDefinitionName>
            <xsl:value-of select="/ns0:BorrarACRequest/ns0:jobDefinitionName"/>
         </tns:jobDefinitionName>
         <xsl:for-each select="/ns0:BorrarACRequest/ns0:paramList">
            <tns:paramList>
               <xsl:value-of select="."/>
            </tns:paramList>
         </xsl:for-each>
      </tns:submitESSJobRequest>
   </xsl:template>
</xsl:stylesheet>
