<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://www.dpworld.com/I004_CrearACBatch/CrearACBatch"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/CrearACBatch.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CrearACBatchRequest"
                                       namespace="http://www.dpworld.com/I004_CrearACBatch/CrearACBatch"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/CrearACBatch.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CrearACBatchRequest"
                                       namespace="http://www.dpworld.com/I004_CrearACBatch/CrearACBatch"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SAT NOV 17 05:23:00 ECT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:CrearACBatchRequest>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchName">
        <ns0:BatchName>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchName/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchName/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchName"/>
        </ns0:BatchName>
      </xsl:if>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchDescription">
        <ns0:BatchDescription>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchDescription/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchDescription/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchDescription"/>
        </ns0:BatchDescription>
      </xsl:if>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:LedgerId">
        <ns0:LedgerId>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:LedgerId/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:LedgerId/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:LedgerId"/>
        </ns0:LedgerId>
      </xsl:if>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName">
        <ns0:AccountingPeriodName>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName"/>
        </ns0:AccountingPeriodName>
      </xsl:if>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingDate">
        <ns0:AccountingDate>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingDate/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingDate/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingDate"/>
        </ns0:AccountingDate>
      </xsl:if>
      <xsl:choose>
        <xsl:when test="not(/ns0:CrearACBatchRequest/ns0:UserSourceName)">
          <ns0:UserSourceName>Payroll</ns0:UserSourceName>
        </xsl:when>
        <xsl:otherwise>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserSourceName">
            <ns0:UserSourceName>
              <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserSourceName/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserSourceName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserSourceName"/>
            </ns0:UserSourceName>
          </xsl:if>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserCategoryName">
        <ns0:UserCategoryName>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserCategoryName/@xsi:nil">
            <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserCategoryName/@xsi:nil"/>
            </xsl:attribute>
          </xsl:if>
          <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserCategoryName"/>
        </ns0:UserCategoryName>
      </xsl:if>
      <xsl:choose>
        <xsl:when test="not(/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag)">
          <ns0:ErrorToSuspenseFlag>true</ns0:ErrorToSuspenseFlag>
        </xsl:when>
        <xsl:otherwise>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag">
            <ns0:ErrorToSuspenseFlag>
              <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag"/>
            </ns0:ErrorToSuspenseFlag>
          </xsl:if>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="not(/ns0:CrearACBatchRequest/ns0:SummaryFlag)">
          <ns0:SummaryFlag>true</ns0:SummaryFlag>
        </xsl:when>
        <xsl:otherwise>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:SummaryFlag">
            <ns0:SummaryFlag>
              <xsl:if test="/ns0:CrearACBatchRequest/ns0:SummaryFlag/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:SummaryFlag/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:SummaryFlag"/>
            </ns0:SummaryFlag>
          </xsl:if>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:choose>
        <xsl:when test="not(/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField)">
          <ns0:ImportDescriptiveFlexField>true</ns0:ImportDescriptiveFlexField>
        </xsl:when>
        <xsl:otherwise>
          <xsl:if test="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField">
            <ns0:ImportDescriptiveFlexField>
              <xsl:if test="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField"/>
            </ns0:ImportDescriptiveFlexField>
          </xsl:if>
        </xsl:otherwise>
      </xsl:choose>
      <xsl:for-each select="/ns0:CrearACBatchRequest/ns0:GlInterface">
        <ns0:GlInterface>
          <xsl:if test="ns0:LedgerId">
            <ns0:LedgerId>
              <xsl:value-of select="ns0:LedgerId"/>
            </ns0:LedgerId>
          </xsl:if>
          <xsl:if test="ns0:PeriodName">
            <ns0:PeriodName>
              <xsl:if test="ns0:PeriodName/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:PeriodName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:PeriodName"/>
            </ns0:PeriodName>
          </xsl:if>
          <xsl:if test="ns0:AccountingDate">
            <ns0:AccountingDate>
              <xsl:value-of select="ns0:AccountingDate"/>
            </ns0:AccountingDate>
          </xsl:if>
          <ns0:UserJeSourceName>Payroll</ns0:UserJeSourceName>
          <ns0:UserJeCategoryName>NOMINA</ns0:UserJeCategoryName>
          <xsl:if test="ns0:GroupId">
            <ns0:GroupId>
              <xsl:value-of select="ns0:GroupId"/>
            </ns0:GroupId>
          </xsl:if>
          <xsl:if test="ns0:ChartOfAccountsId">
            <ns0:ChartOfAccountsId>
              <xsl:if test="ns0:ChartOfAccountsId/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:ChartOfAccountsId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:ChartOfAccountsId"/>
            </ns0:ChartOfAccountsId>
          </xsl:if>
          <xsl:if test="ns0:BalanceType">
            <ns0:BalanceType>
              <xsl:value-of select="ns0:BalanceType"/>
            </ns0:BalanceType>
          </xsl:if>
          <xsl:if test="ns0:AccountedCr">
            <ns0:AccountedCr>
              <xsl:if test="ns0:AccountedCr/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:AccountedCr/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:AccountedCr"/>
            </ns0:AccountedCr>
          </xsl:if>
          <xsl:if test="ns0:AccountedDr">
            <ns0:AccountedDr>
              <xsl:if test="ns0:AccountedDr/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:AccountedDr/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:AccountedDr"/>
            </ns0:AccountedDr>
          </xsl:if>
          <xsl:if test="ns0:StatisticalValue">
            <ns0:StatisticalValue>
              <xsl:if test="ns0:StatisticalValue/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:StatisticalValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:StatisticalValue"/>
            </ns0:StatisticalValue>
          </xsl:if>
          <xsl:if test="ns0:UserCurrencyConversionType">
            <ns0:UserCurrencyConversionType>
              <xsl:if test="ns0:UserCurrencyConversionType/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:UserCurrencyConversionType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:UserCurrencyConversionType"/>
            </ns0:UserCurrencyConversionType>
          </xsl:if>
          <xsl:if test="ns0:CurrencyConversionDate">
            <ns0:CurrencyConversionDate>
              <xsl:if test="ns0:CurrencyConversionDate/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:CurrencyConversionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:CurrencyConversionDate"/>
            </ns0:CurrencyConversionDate>
          </xsl:if>
          <xsl:if test="ns0:CurrencyConversionRate">
            <ns0:CurrencyConversionRate>
              <xsl:if test="ns0:CurrencyConversionRate/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:CurrencyConversionRate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:CurrencyConversionRate"/>
            </ns0:CurrencyConversionRate>
          </xsl:if>
          <xsl:if test="ns0:CurrencyConversionType">
            <ns0:CurrencyConversionType>
              <xsl:if test="ns0:CurrencyConversionType/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:CurrencyConversionType/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:CurrencyConversionType"/>
            </ns0:CurrencyConversionType>
          </xsl:if>
          <xsl:if test="ns0:Reference1">
            <ns0:Reference1>
              <xsl:if test="ns0:Reference1/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference1/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference1"/>
            </ns0:Reference1>
          </xsl:if>
          <xsl:if test="ns0:Reference2">
            <ns0:Reference2>
              <xsl:if test="ns0:Reference2/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference2"/>
            </ns0:Reference2>
          </xsl:if>
          <xsl:if test="ns0:Reference3">
            <ns0:Reference3>
              <xsl:if test="ns0:Reference3/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference3"/>
            </ns0:Reference3>
          </xsl:if>
          <xsl:if test="ns0:Reference6">
            <ns0:Reference6>
              <xsl:if test="ns0:Reference6/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference6/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference6"/>
            </ns0:Reference6>
          </xsl:if>
          <xsl:if test="ns0:Reference7">
            <ns0:Reference7>
              <xsl:if test="ns0:Reference7/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference7/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference7"/>
            </ns0:Reference7>
          </xsl:if>
          <xsl:if test="ns0:Reference8">
            <ns0:Reference8>
              <xsl:if test="ns0:Reference8/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference8/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference8"/>
            </ns0:Reference8>
          </xsl:if>
          <xsl:if test="ns0:Reference9">
            <ns0:Reference9>
              <xsl:if test="ns0:Reference9/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference9/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference9"/>
            </ns0:Reference9>
          </xsl:if>
          <xsl:if test="ns0:Reference10">
            <ns0:Reference10>
              <xsl:if test="ns0:Reference10/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference10/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference10"/>
            </ns0:Reference10>
          </xsl:if>
          <xsl:if test="ns0:Reference11">
            <ns0:Reference11>
              <xsl:if test="ns0:Reference11/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference11/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference11"/>
            </ns0:Reference11>
          </xsl:if>
          <xsl:if test="ns0:Reference12">
            <ns0:Reference12>
              <xsl:if test="ns0:Reference12/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference12/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference12"/>
            </ns0:Reference12>
          </xsl:if>
          <xsl:if test="ns0:Reference13">
            <ns0:Reference13>
              <xsl:if test="ns0:Reference13/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference13/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference13"/>
            </ns0:Reference13>
          </xsl:if>
          <xsl:if test="ns0:Reference14">
            <ns0:Reference14>
              <xsl:if test="ns0:Reference14/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference14/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference14"/>
            </ns0:Reference14>
          </xsl:if>
          <xsl:if test="ns0:Reference15">
            <ns0:Reference15>
              <xsl:if test="ns0:Reference15/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference15/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference15"/>
            </ns0:Reference15>
          </xsl:if>
          <xsl:if test="ns0:Reference16">
            <ns0:Reference16>
              <xsl:if test="ns0:Reference16/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference16/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference16"/>
            </ns0:Reference16>
          </xsl:if>
          <xsl:if test="ns0:Reference17">
            <ns0:Reference17>
              <xsl:if test="ns0:Reference17/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference17/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference17"/>
            </ns0:Reference17>
          </xsl:if>
          <xsl:if test="ns0:Reference18">
            <ns0:Reference18>
              <xsl:if test="ns0:Reference18/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference18/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference18"/>
            </ns0:Reference18>
          </xsl:if>
          <xsl:if test="ns0:Reference19">
            <ns0:Reference19>
              <xsl:if test="ns0:Reference19/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference19/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference19"/>
            </ns0:Reference19>
          </xsl:if>
          <xsl:if test="ns0:Reference20">
            <ns0:Reference20>
              <xsl:if test="ns0:Reference20/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference20/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference20"/>
            </ns0:Reference20>
          </xsl:if>
          <xsl:if test="ns0:Reference21">
            <ns0:Reference21>
              <xsl:if test="ns0:Reference21/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference21/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference21"/>
            </ns0:Reference21>
          </xsl:if>
          <xsl:if test="ns0:Reference22">
            <ns0:Reference22>
              <xsl:if test="ns0:Reference22/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference22/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference22"/>
            </ns0:Reference22>
          </xsl:if>
          <xsl:if test="ns0:Reference23">
            <ns0:Reference23>
              <xsl:if test="ns0:Reference23/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference23/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference23"/>
            </ns0:Reference23>
          </xsl:if>
          <xsl:if test="ns0:Reference24">
            <ns0:Reference24>
              <xsl:if test="ns0:Reference24/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference24/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference24"/>
            </ns0:Reference24>
          </xsl:if>
          <xsl:if test="ns0:Reference25">
            <ns0:Reference25>
              <xsl:if test="ns0:Reference25/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference25/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference25"/>
            </ns0:Reference25>
          </xsl:if>
          <xsl:if test="ns0:Reference26">
            <ns0:Reference26>
              <xsl:if test="ns0:Reference26/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference26/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference26"/>
            </ns0:Reference26>
          </xsl:if>
          <xsl:if test="ns0:Reference27">
            <ns0:Reference27>
              <xsl:if test="ns0:Reference27/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference27/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference27"/>
            </ns0:Reference27>
          </xsl:if>
          <xsl:if test="ns0:Reference28">
            <ns0:Reference28>
              <xsl:if test="ns0:Reference28/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference28/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference28"/>
            </ns0:Reference28>
          </xsl:if>
          <xsl:if test="ns0:Reference29">
            <ns0:Reference29>
              <xsl:if test="ns0:Reference29/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference29/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference29"/>
            </ns0:Reference29>
          </xsl:if>
          <xsl:if test="ns0:Reference30">
            <ns0:Reference30>
              <xsl:if test="ns0:Reference30/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:Reference30/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:Reference30"/>
            </ns0:Reference30>
          </xsl:if>
          <xsl:if test="ns0:ReferenceDate">
            <ns0:ReferenceDate>
              <xsl:if test="ns0:ReferenceDate/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:ReferenceDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:ReferenceDate"/>
            </ns0:ReferenceDate>
          </xsl:if>
          <xsl:if test="ns0:AttributeCategory">
            <ns0:AttributeCategory>
              <xsl:if test="ns0:AttributeCategory/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:AttributeCategory/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:AttributeCategory"/>
            </ns0:AttributeCategory>
          </xsl:if>
          <xsl:if test="ns0:AttributeCategory2">
            <ns0:AttributeCategory2>
              <xsl:if test="ns0:AttributeCategory2/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:AttributeCategory2/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:AttributeCategory2"/>
            </ns0:AttributeCategory2>
          </xsl:if>
          <xsl:if test="ns0:AttributeCategory3">
            <ns0:AttributeCategory3>
              <xsl:if test="ns0:AttributeCategory3/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:AttributeCategory3/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:AttributeCategory3"/>
            </ns0:AttributeCategory3>
          </xsl:if>
          <xsl:if test="ns0:BalancingSegmentValue">
            <ns0:BalancingSegmentValue>
              <xsl:if test="ns0:BalancingSegmentValue/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:BalancingSegmentValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:BalancingSegmentValue"/>
            </ns0:BalancingSegmentValue>
          </xsl:if>
          <xsl:if test="ns0:DescrFlexErrorMessage">
            <ns0:DescrFlexErrorMessage>
              <xsl:if test="ns0:DescrFlexErrorMessage/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:DescrFlexErrorMessage/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:DescrFlexErrorMessage"/>
            </ns0:DescrFlexErrorMessage>
          </xsl:if>
          <xsl:if test="ns0:GlSlLinkId">
            <ns0:GlSlLinkId>
              <xsl:if test="ns0:GlSlLinkId/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:GlSlLinkId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:GlSlLinkId"/>
            </ns0:GlSlLinkId>
          </xsl:if>
          <xsl:if test="ns0:GlSlLinkTable">
            <ns0:GlSlLinkTable>
              <xsl:if test="ns0:GlSlLinkTable/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:GlSlLinkTable/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:GlSlLinkTable"/>
            </ns0:GlSlLinkTable>
          </xsl:if>
          <xsl:choose>
            <xsl:when test="not(/ns0:JeCategoryName)">
              <ns0:JeCategoryName>NOMINA</ns0:JeCategoryName>
            </xsl:when>
            <xsl:otherwise>
              <xsl:if test="ns0:JeCategoryName">
                <ns0:JeCategoryName>
                  <xsl:if test="ns0:JeCategoryName/@xsi:nil">
                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                      <xsl:value-of select="ns0:JeCategoryName/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:JeCategoryName"/>
                </ns0:JeCategoryName>
              </xsl:if>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="not(/ns0:JeSourceName)">
              <ns0:JeSourceName>Payroll</ns0:JeSourceName>
            </xsl:when>
            <xsl:otherwise>
              <xsl:if test="ns0:JeSourceName">
                <ns0:JeSourceName>
                  <xsl:if test="ns0:JeSourceName/@xsi:nil">
                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                      <xsl:value-of select="ns0:JeSourceName/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:JeSourceName"/>
                </ns0:JeSourceName>
              </xsl:if>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:if test="ns0:JgzzReconReference">
            <ns0:JgzzReconReference>
              <xsl:if test="ns0:JgzzReconReference/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:JgzzReconReference/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:JgzzReconReference"/>
            </ns0:JgzzReconReference>
          </xsl:if>
          <xsl:if test="ns0:ManagementSegmentValue">
            <ns0:ManagementSegmentValue>
              <xsl:if test="ns0:ManagementSegmentValue/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:ManagementSegmentValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:ManagementSegmentValue"/>
            </ns0:ManagementSegmentValue>
          </xsl:if>
          <xsl:if test="ns0:OriginatingBalSegValue">
            <ns0:OriginatingBalSegValue>
              <xsl:if test="ns0:OriginatingBalSegValue/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:OriginatingBalSegValue/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:OriginatingBalSegValue"/>
            </ns0:OriginatingBalSegValue>
          </xsl:if>
          <xsl:if test="ns0:SetOfBooksId">
            <ns0:SetOfBooksId>
              <xsl:if test="ns0:SetOfBooksId/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:SetOfBooksId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:SetOfBooksId"/>
            </ns0:SetOfBooksId>
          </xsl:if>
          <xsl:if test="ns0:TaxCode">
            <ns0:TaxCode>
              <xsl:if test="ns0:TaxCode/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:TaxCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:TaxCode"/>
            </ns0:TaxCode>
          </xsl:if>
          <xsl:if test="ns0:TransactionDate">
            <ns0:TransactionDate>
              <xsl:if test="ns0:TransactionDate/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:TransactionDate"/>
            </ns0:TransactionDate>
          </xsl:if>
          <xsl:if test="ns0:USSGLTransactionCode">
            <ns0:USSGLTransactionCode>
              <xsl:if test="ns0:USSGLTransactionCode/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:USSGLTransactionCode/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:USSGLTransactionCode"/>
            </ns0:USSGLTransactionCode>
          </xsl:if>
          <xsl:if test="ns0:GlInterfaceId">
            <ns0:GlInterfaceId>
              <xsl:if test="ns0:GlInterfaceId/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:GlInterfaceId/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:GlInterfaceId"/>
            </ns0:GlInterfaceId>
          </xsl:if>
          <xsl:if test="ns0:LegalEntityIdentifier">
            <ns0:LegalEntityIdentifier>
              <xsl:if test="ns0:LegalEntityIdentifier/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:LegalEntityIdentifier/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:LegalEntityIdentifier"/>
            </ns0:LegalEntityIdentifier>
          </xsl:if>
          <xsl:if test="ns0:LedgerName">
            <ns0:LedgerName>
              <xsl:if test="ns0:LedgerName/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:LedgerName/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:LedgerName"/>
            </ns0:LedgerName>
          </xsl:if>
        </ns0:GlInterface>
      </xsl:for-each>
      <ns0:Massives>
        <xsl:for-each select="/ns0:CrearACBatchRequest/ns0:Massives/ns0:Massive">
          <ns0:Massive>
            <xsl:if test="ns0:Segment1">
              <ns0:Segment1>
                <xsl:if test="ns0:Segment1/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment1/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment1"/>
              </ns0:Segment1>
            </xsl:if>
            <xsl:if test="ns0:Segment2">
              <ns0:Segment2>
                <xsl:if test="ns0:Segment2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment2"/>
              </ns0:Segment2>
            </xsl:if>
            <xsl:if test="ns0:Segment3">
              <ns0:Segment3>
                <xsl:if test="ns0:Segment3/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment3/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment3"/>
              </ns0:Segment3>
            </xsl:if>
            <xsl:if test="ns0:Segment4">
              <ns0:Segment4>
                <xsl:if test="ns0:Segment4/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment4/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment4"/>
              </ns0:Segment4>
            </xsl:if>
            <xsl:if test="ns0:Segment5">
              <ns0:Segment5>
                <xsl:if test="ns0:Segment5/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment5/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment5"/>
              </ns0:Segment5>
            </xsl:if>
            <xsl:if test="ns0:Segment6">
              <ns0:Segment6>
                <xsl:if test="ns0:Segment6/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment6/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment6"/>
              </ns0:Segment6>
            </xsl:if>
            <xsl:if test="ns0:Segment7">
              <ns0:Segment7>
                <xsl:if test="ns0:Segment7/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment7/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment7"/>
              </ns0:Segment7>
            </xsl:if>
            <xsl:if test="ns0:Segment8">
              <ns0:Segment8>
                <xsl:if test="ns0:Segment8/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment8/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment8"/>
              </ns0:Segment8>
            </xsl:if>
            <xsl:if test="ns0:Segment9">
              <ns0:Segment9>
                <xsl:if test="ns0:Segment9/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment9/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment9"/>
              </ns0:Segment9>
            </xsl:if>
            <xsl:if test="ns0:Segment10">
              <ns0:Segment10>
                <xsl:if test="ns0:Segment10/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment10/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment10"/>
              </ns0:Segment10>
            </xsl:if>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment11)">
                <ns0:Segment11></ns0:Segment11>
              </xsl:when>
              <xsl:otherwise>
                  <xsl:if test="ns0:Segment11">
                    <ns0:Segment11>
                      <xsl:if test="ns0:Segment11/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                          <xsl:value-of select="ns0:Segment11/@xsi:nil"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="ns0:Segment11"/>
                    </ns0:Segment11>
                  </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment12)">
                <ns0:Segment12></ns0:Segment12>
              </xsl:when>
              <xsl:otherwise>
              <xsl:if test="ns0:Segment12">
                <ns0:Segment12>
                  <xsl:if test="ns0:Segment12/@xsi:nil">
                    <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                      <xsl:value-of select="ns0:Segment12/@xsi:nil"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="ns0:Segment12"/>
                </ns0:Segment12>
              </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment13)">
                <ns0:Segment13></ns0:Segment13>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment13">
                  <ns0:Segment13>
                    <xsl:if test="ns0:Segment13/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment13/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment13"/>
                  </ns0:Segment13>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment14)">
                <ns0:Segment14></ns0:Segment14>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment14">
                  <ns0:Segment14>
                    <xsl:if test="ns0:Segment14/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment14/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment14"/>
                  </ns0:Segment14>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment15)">
                <ns0:Segment15></ns0:Segment15>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment15">
                  <ns0:Segment15>
                    <xsl:if test="ns0:Segment15/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment15/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment15"/>
                  </ns0:Segment15>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment16)">
                <ns0:Segment16></ns0:Segment16>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment16">
                  <ns0:Segment16>
                    <xsl:if test="ns0:Segment16/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment16/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment16"/>
                  </ns0:Segment16>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment17)">
                <ns0:Segment17></ns0:Segment17>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment17">
                  <ns0:Segment17>
                    <xsl:if test="ns0:Segment17/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment17/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment17"/>
                  </ns0:Segment17>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment18)">
                <ns0:Segment18></ns0:Segment18>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment18">
                  <ns0:Segment18>
                    <xsl:if test="ns0:Segment18/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment18/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment18"/>
                  </ns0:Segment18>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment19)">
                <ns0:Segment19></ns0:Segment19>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment19">
                  <ns0:Segment19>
                    <xsl:if test="ns0:Segment19/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment19/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment19"/>
                  </ns0:Segment19>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment20)">
                <ns0:Segment20></ns0:Segment20>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment20">
                  <ns0:Segment20>
                    <xsl:if test="ns0:Segment20/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment20/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment20"/>
                  </ns0:Segment20>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment21)">
                <ns0:Segment21></ns0:Segment21>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment21">
                  <ns0:Segment21>
                    <xsl:if test="ns0:Segment21/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment21/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment21"/>
                  </ns0:Segment21>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment22)">
                <ns0:Segment22></ns0:Segment22>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment22">
                  <ns0:Segment22>
                    <xsl:if test="ns0:Segment22/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment22/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment22"/>
                  </ns0:Segment22>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment23)">
                <ns0:Segment23></ns0:Segment23>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment23">
                  <ns0:Segment23>
                    <xsl:if test="ns0:Segment23/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment23/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment23"/>
                  </ns0:Segment23>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment24)">
                <ns0:Segment24></ns0:Segment24>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment24">
                  <ns0:Segment24>
                    <xsl:if test="ns0:Segment24/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment24/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment24"/>
                  </ns0:Segment24>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment25)">
                <ns0:Segment25></ns0:Segment25>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment25">
                  <ns0:Segment25>
                    <xsl:if test="ns0:Segment25/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment25/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment25"/>
                  </ns0:Segment25>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment26)">
                <ns0:Segment26></ns0:Segment26>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment26">
                  <ns0:Segment26>
                    <xsl:if test="ns0:Segment26/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment26/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment26"/>
                  </ns0:Segment26>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment27)">
                <ns0:Segment27></ns0:Segment27>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment27">
                  <ns0:Segment27>
                    <xsl:if test="ns0:Segment27/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment27/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment27"/>
                  </ns0:Segment27>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment28)">
                <ns0:Segment28></ns0:Segment28>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment28">
                  <ns0:Segment28>
                    <xsl:if test="ns0:Segment28/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment28/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment28"/>
                  </ns0:Segment28>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment29)">
                <ns0:Segment29></ns0:Segment29>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment29">
                  <ns0:Segment29>
                    <xsl:if test="ns0:Segment29/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment29/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment29"/>
                  </ns0:Segment29>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Segment30)">
                <ns0:Segment30></ns0:Segment30>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Segment30">
                  <ns0:Segment30>
                    <xsl:if test="ns0:Segment30/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Segment30/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Segment30"/>
                  </ns0:Segment30>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns0:Attribute1">
              <ns0:Attribute1>
                <xsl:if test="ns0:Attribute1/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute1/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute1"/>
              </ns0:Attribute1>
            </xsl:if>
            <xsl:if test="ns0:Attribute2">
              <ns0:Attribute2>
                <xsl:if test="ns0:Attribute2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute2"/>
              </ns0:Attribute2>
            </xsl:if>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute3)">
                <ns0:Attribute3></ns0:Attribute3>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute3">
                  <ns0:Attribute3>
                    <xsl:if test="ns0:Attribute3/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute3/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute3"/>
                  </ns0:Attribute3>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute4)">
                <ns0:Attribute4></ns0:Attribute4>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute4">
                  <ns0:Attribute4>
                    <xsl:if test="ns0:Attribute4/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute4/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute4"/>
                  </ns0:Attribute4>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute5)">
                <ns0:Attribute5></ns0:Attribute5>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute5">
                  <ns0:Attribute5>
                    <xsl:if test="ns0:Attribute5/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute5/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute5"/>
                  </ns0:Attribute5>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute6)">
                <ns0:Attribute6></ns0:Attribute6>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute6">
                  <ns0:Attribute6>
                    <xsl:if test="ns0:Attribute6/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute6/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute6"/>
                  </ns0:Attribute6>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute7)">
                <ns0:Attribute7></ns0:Attribute7>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute7">
                  <ns0:Attribute7>
                    <xsl:if test="ns0:Attribute7/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute7/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute7"/>
                  </ns0:Attribute7>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute8)">
                <ns0:Attribute8></ns0:Attribute8>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute8">
                  <ns0:Attribute8>
                    <xsl:if test="ns0:Attribute8/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute8/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute8"/>
                  </ns0:Attribute8>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute9)">
                <ns0:Attribute9></ns0:Attribute9>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute9">
                  <ns0:Attribute9>
                    <xsl:if test="ns0:Attribute9/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute9/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute9"/>
                  </ns0:Attribute9>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute10)">
                <ns0:Attribute10></ns0:Attribute10>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute10">
                  <ns0:Attribute10>
                    <xsl:if test="ns0:Attribute10/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute10/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute10"/>
                  </ns0:Attribute10>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute11)">
                <ns0:Attribute11></ns0:Attribute11>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute11">
                  <ns0:Attribute11>
                    <xsl:if test="ns0:Attribute11/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute11/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute11"/>
                  </ns0:Attribute11>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute12)">
                <ns0:Attribute12></ns0:Attribute12>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute12">
                  <ns0:Attribute12>
                    <xsl:if test="ns0:Attribute12/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute12/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute12"/>
                  </ns0:Attribute12>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute13)">
                <ns0:Attribute13></ns0:Attribute13>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute13">
                  <ns0:Attribute13>
                    <xsl:if test="ns0:Attribute13/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute13/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute13"/>
                  </ns0:Attribute13>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute14)">
                <ns0:Attribute14></ns0:Attribute14>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute14">
                  <ns0:Attribute14>
                    <xsl:if test="ns0:Attribute14/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute14/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute14"/>
                  </ns0:Attribute14>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute15)">
                <ns0:Attribute15></ns0:Attribute15>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute15">
                  <ns0:Attribute15>
                    <xsl:if test="ns0:Attribute15/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute15/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute15"/>
                  </ns0:Attribute15>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute16)">
                <ns0:Attribute16></ns0:Attribute16>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute16">
                  <ns0:Attribute16>
                    <xsl:if test="ns0:Attribute16/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute16/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute16"/>
                  </ns0:Attribute16>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute17)">
                <ns0:Attribute17></ns0:Attribute17>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute17">
                  <ns0:Attribute17>
                    <xsl:if test="ns0:Attribute17/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute17/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute17"/>
                  </ns0:Attribute17>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute18)">
                <ns0:Attribute18></ns0:Attribute18>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute18">
                  <ns0:Attribute18>
                    <xsl:if test="ns0:Attribute18/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute18/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute18"/>
                  </ns0:Attribute18>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute19)">
                <ns0:Attribute19></ns0:Attribute19>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute19">
                  <ns0:Attribute19>
                    <xsl:if test="ns0:Attribute19/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute19/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute19"/>
                  </ns0:Attribute19>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(ns0:Attribute20)">
                <ns0:Attribute20></ns0:Attribute20>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:Attribute20">
                  <ns0:Attribute20>
                    <xsl:if test="ns0:Attribute20/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:Attribute20/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:Attribute20"/>
                  </ns0:Attribute20>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns0:CurrencyCode">
              <ns0:CurrencyCode>
                <xsl:value-of select="ns0:CurrencyCode"/>
              </ns0:CurrencyCode>
            </xsl:if>
            <xsl:if test="ns0:EnteredCrAmount">
                  <ns0:EnteredCrAmount currencyCode="USD">
                    <xsl:if test="ns0:EnteredCrAmount/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:EnteredCrAmount/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="translate(ns0:EnteredCrAmount,',','.')"/>
                  </ns0:EnteredCrAmount>
            </xsl:if>
            <xsl:if test="ns0:EnteredDrAmount">
                  <ns0:EnteredDrAmount currencyCode="USD">
                    <xsl:if test="ns0:EnteredDrAmount/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:EnteredDrAmount/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="translate(ns0:EnteredDrAmount,',','.')"/>
                  </ns0:EnteredDrAmount>
             </xsl:if>
            <xsl:choose>
              <xsl:when test="not(ns0:CodeCombinationId)">
                <ns0:CodeCombinationId></ns0:CodeCombinationId>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:CodeCombinationId">
                  <ns0:CodeCombinationId>
                    <xsl:if test="ns0:CodeCombinationId/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:CodeCombinationId/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:CodeCombinationId"/>
                  </ns0:CodeCombinationId>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
          </ns0:Massive>
        </xsl:for-each>
      </ns0:Massives>
    </ns0:CrearACBatchRequest>
  </xsl:template>
</xsl:stylesheet>
