<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://www.dpworld.com/ProcesarAsientoContable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.oracle.com/bpel/extension">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDL_SCA/CrearAsientoContable.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CrearACRequest"
                                       namespace="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://localhost:7101/soa-infra/services/default/I002_SCAProcesarAC!1.0/WSDL_SCA/ProcesarAsientoContable.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProcesarACRequest"
                                       namespace="http://www.dpworld.com/ProcesarAsientoContable"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU NOV 08 22:04:13 ECT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ProcesarACRequest>
      <tns:jobPackageName>
        <xsl:value-of select='"/oracle/apps/ess/financials/generalLedger/programs/common/"'/>
      </tns:jobPackageName>
      <tns:jobDefinitionName>
        <xsl:value-of select='"JournalImportLauncher"'/>
      </tns:jobDefinitionName>
      <xsl:choose>
        <xsl:when test="/ns0:CrearACRequest/ns0:GlInterface/ns0:LedgerId = 300000001576006">
          <tns:paramList>
            <xsl:value-of select='"300000001576011"'/>
          </tns:paramList>
        </xsl:when>
        <xsl:otherwise>
          <tns:paramList>
            <xsl:value-of select='"300000001576020"'/>
          </tns:paramList>
        </xsl:otherwise>
      </xsl:choose>
      <tns:paramList>
        <xsl:value-of select='"Payroll"'/>
      </tns:paramList>
      <tns:paramList>
        <xsl:value-of select="/ns0:CrearACRequest/ns0:GlInterface/ns0:LedgerId"/>
      </tns:paramList>
      <tns:paramList>
        <xsl:value-of select="/ns0:CrearACRequest/ns0:GlInterface/ns0:GroupId"/>
      </tns:paramList>
      <tns:paramList>
        <xsl:value-of select='"N"'/>
      </tns:paramList>
      <tns:paramList>
        <xsl:value-of select='"N"'/>
      </tns:paramList>
      <tns:paramList>
        <xsl:value-of select='"O"'/>
      </tns:paramList>
    </tns:ProcesarACRequest>
  </xsl:template>
</xsl:stylesheet>
