<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:tns="http://www.dpworld.com/SOA_DPWORLD/I003_BorrarAsientoContable" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDL_SCA/CrearAsientoContable.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CrearACRequest" namespace="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://localhost:7101/soa-infra/services/default/I003_SCABorrarAC!1.0/WSDL_SCA/BorrarAsientoContable.wsdl"/>
            <oracle-xsl-mapper:rootElement name="BorrarACRequest" namespace="http://www.dpworld.com/SOA_DPWORLD/I003_BorrarAsientoContable"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [FRI NOV 09 04:53:37 ECT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:BorrarACRequest>
         <tns:jobPackageName>
            <xsl:value-of select="&quot;/oracle/apps/ess/financials/commonModules/shared/common/interfaceLoader/&quot;"/>
         </tns:jobPackageName>
         <tns:jobDefinitionName>
            <xsl:value-of select="&quot;InterfaceLoaderPurge&quot;"/>
         </tns:jobDefinitionName>
         <tns:paramList>
            <xsl:value-of select="&quot;15&quot;"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:LedgerId"/>
         </tns:paramList>
         <tns:paramList>
            <xsl:value-of select="&quot;#NULL&quot;"/>
         </tns:paramList>
           <tns:paramList>
            <xsl:value-of select="&quot;#NULL&quot;"/>
         </tns:paramList>
           <tns:paramList>
            <xsl:value-of select="&quot;#NULL&quot;"/>
         </tns:paramList>
           <tns:paramList>
            <xsl:value-of select="&quot;ORA_FBDI&quot;"/>
         </tns:paramList>
      </tns:BorrarACRequest>
   </xsl:template>
</xsl:stylesheet>
