<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:tns="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"
                exclude-result-prefixes="xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:orafault="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0"
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/"
                xmlns:ns3="http://xmlns.oracle.com/adf/svc/types/" xmlns:ns4="commonj.sdo/xml"
                xmlns:ns5="commonj.sdo/java" xmlns:ns6="commonj.sdo"
                xmlns:ns2="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDL_SCA/CrearAsientoContable.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CrearACRequest"
                                       namespace="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="https://eggx-test.fa.us6.oraclecloud.com:443/fscmService/JournalImportService?wsdl"/>
        <oracle-xsl-mapper:rootElement name="importJournals"
                                       namespace="http://xmlns.oracle.com/apps/financials/generalLedger/journals/desktopEntry/journalImportService/types/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [THU NOV 22 20:52:06 ECT 2018].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:importJournals>
      <tns:interfaceRows>
        <xsl:if test="/ns0:CrearACRequest/ns0:BatchName">
          <ns2:BatchName>
            <xsl:if test="/ns0:CrearACRequest/ns0:BatchName/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:BatchName/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:BatchName"/>
          </ns2:BatchName>
        </xsl:if>
        <xsl:if test="/ns0:CrearACRequest/ns0:BatchDescription">
          <ns2:BatchDescription>
            <xsl:if test="/ns0:CrearACRequest/ns0:BatchDescription/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:BatchDescription/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:BatchDescription"/>
          </ns2:BatchDescription>
        </xsl:if>
        <xsl:if test="/ns0:CrearACRequest/ns0:LedgerId">
          <ns2:LedgerId>
            <xsl:if test="/ns0:CrearACRequest/ns0:LedgerId/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:LedgerId/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:LedgerId"/>
          </ns2:LedgerId>
        </xsl:if>
        <xsl:if test="/ns0:CrearACRequest/ns0:AccountingPeriodName">
          <ns2:AccountingPeriodName>
            <xsl:if test="/ns0:CrearACRequest/ns0:AccountingPeriodName/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:AccountingPeriodName/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:AccountingPeriodName"/>
          </ns2:AccountingPeriodName>
        </xsl:if>
        <xsl:if test="/ns0:CrearACRequest/ns0:AccountingDate">
          <ns2:AccountingDate>
            <xsl:if test="/ns0:CrearACRequest/ns0:AccountingDate/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:AccountingDate/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:AccountingDate"/>
          </ns2:AccountingDate>
        </xsl:if>
        <xsl:choose>
          <xsl:when test="not(/ns0:CrearACRequest/ns0:UserSourceName)">
            <ns2:UserSourceName>Payroll</ns2:UserSourceName>
          </xsl:when>
          <xsl:otherwise>
            <xsl:if test="/ns0:CrearACRequest/ns0:UserSourceName">
              <ns2:UserSourceName>
                <xsl:value-of select="/ns0:CrearACRequest/ns0:UserSourceName"/>
              </ns2:UserSourceName>
            </xsl:if>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:if test="/ns0:CrearACRequest/ns0:UserCategoryName">
          <ns2:UserCategoryName>
            <xsl:if test="/ns0:CrearACRequest/ns0:UserCategoryName/@xsi:nil">
              <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                <xsl:value-of select="/ns0:CrearACRequest/ns0:UserCategoryName/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:CrearACRequest/ns0:UserCategoryName"/>
          </ns2:UserCategoryName>
        </xsl:if>
        <xsl:choose>
          <xsl:when test="not(/ns0:CrearACRequest/ns0:ErrorToSuspenseFlag)">
            <ns2:ErrorToSuspenseFlag>true</ns2:ErrorToSuspenseFlag>
          </xsl:when>
          <xsl:otherwise>
            <xsl:if test="/ns0:CrearACRequest/ns0:ErrorToSuspenseFlag">
              <ns2:ErrorToSuspenseFlag>
                <xsl:if test="/ns0:CrearACRequest/ns0:ErrorToSuspenseFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="/ns0:CrearACRequest/ns0:ErrorToSuspenseFlag/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="/ns0:CrearACRequest/ns0:ErrorToSuspenseFlag"/>
              </ns2:ErrorToSuspenseFlag>
            </xsl:if>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="not(/ns0:CrearACRequest/ns0:SummaryFlag)">
            <ns2:SummaryFlag>true</ns2:SummaryFlag>
          </xsl:when>
          <xsl:otherwise>
            <xsl:if test="/ns0:CrearACRequest/ns0:SummaryFlag">
              <ns2:SummaryFlag>
                <xsl:if test="/ns0:CrearACRequest/ns0:SummaryFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="/ns0:CrearACRequest/ns0:SummaryFlag/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="/ns0:CrearACRequest/ns0:SummaryFlag"/>
              </ns2:SummaryFlag>
            </xsl:if>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:choose>
          <xsl:when test="not(/ns0:CrearACRequest/ns0:ImportDescriptiveFlexField)">
            <ns2:ImportDescriptiveFlexField>true</ns2:ImportDescriptiveFlexField>
          </xsl:when>
          <xsl:otherwise>
            <xsl:if test="/ns0:CrearACRequest/ns0:ImportDescriptiveFlexField">
              <ns2:ImportDescriptiveFlexField>
                <xsl:if test="/ns0:CrearACRequest/ns0:ImportDescriptiveFlexField/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="/ns0:CrearACRequest/ns0:ImportDescriptiveFlexField/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="/ns0:CrearACRequest/ns0:ImportDescriptiveFlexField"/>
              </ns2:ImportDescriptiveFlexField>
            </xsl:if>
          </xsl:otherwise>
        </xsl:choose>
        <xsl:for-each select="/ns0:CrearACRequest/ns0:GlInterface">
          <ns2:GlInterface>
            <xsl:if test="ns0:Reference4">
              <ns2:Reference4>
                <xsl:if test="ns0:Reference4/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference4/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference4"/>
              </ns2:Reference4>
            </xsl:if>
            <ns2:Reference5>
              <xsl:value-of select="concat(/ns0:CrearACRequest/ns0:BatchDescription, ' ' , /ns0:CrearACRequest/ns0:AccountingPeriodName)" />
            </ns2:Reference5>
            <xsl:if test="ns0:LedgerId">
              <ns2:LedgerId>
                <xsl:value-of select="ns0:LedgerId"/>
              </ns2:LedgerId>
            </xsl:if>
            <xsl:if test="ns0:PeriodName">
              <ns2:PeriodName>
                <xsl:if test="ns0:PeriodName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:PeriodName/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:PeriodName"/>
              </ns2:PeriodName>
            </xsl:if>
            <xsl:if test="ns0:AccountingDate">
              <ns2:AccountingDate>
                <xsl:value-of select="ns0:AccountingDate"/>
              </ns2:AccountingDate>
            </xsl:if>
            <xsl:choose>
              <xsl:when test="not(/ns0:CrearACRequest/ns0:UserJeSourceName)">
                <ns0:UserJeSourceName>Payroll</ns0:UserJeSourceName>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:UserJeSourceName">
                  <ns2:UserJeSourceName>
                    <xsl:value-of select="ns0:UserJeSourceName"/>
                  </ns2:UserJeSourceName>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns0:UserJeCategoryName">
              <ns2:UserJeCategoryName>
                <xsl:value-of select="ns0:UserJeCategoryName"/>
              </ns2:UserJeCategoryName>
            </xsl:if>
            <xsl:if test="ns0:GroupId">
              <ns2:GroupId>
                <xsl:value-of select="ns0:GroupId"/>
              </ns2:GroupId>
            </xsl:if>
            <xsl:if test="ns0:ChartOfAccountsId">
              <ns2:ChartOfAccountsId>
                <xsl:if test="ns0:ChartOfAccountsId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:ChartOfAccountsId/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:ChartOfAccountsId"/>
              </ns2:ChartOfAccountsId>
            </xsl:if>
            <xsl:if test="ns0:BalanceType">
              <ns2:BalanceType>
                <xsl:value-of select="ns0:BalanceType"/>
              </ns2:BalanceType>
            </xsl:if>
            <xsl:if test="ns0:CodeCombinationId">
              <ns2:CodeCombinationId>
                <xsl:if test="ns0:CodeCombinationId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:CodeCombinationId/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:CodeCombinationId"/>
              </ns2:CodeCombinationId>
            </xsl:if>
            <xsl:if test="ns0:Segment1">
              <ns2:Segment1>
                <xsl:if test="ns0:Segment1/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment1/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment1"/>
              </ns2:Segment1>
            </xsl:if>
            <xsl:if test="ns0:Segment2">
              <ns2:Segment2>
                <xsl:if test="ns0:Segment2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment2"/>
              </ns2:Segment2>
            </xsl:if>
            <xsl:if test="ns0:Segment3">
              <ns2:Segment3>
                <xsl:if test="ns0:Segment3/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment3/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment3"/>
              </ns2:Segment3>
            </xsl:if>
            <xsl:if test="ns0:Segment4">
              <ns2:Segment4>
                <xsl:if test="ns0:Segment4/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment4/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment4"/>
              </ns2:Segment4>
            </xsl:if>
            <xsl:if test="ns0:Segment5">
              <ns2:Segment5>
                <xsl:if test="ns0:Segment5/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment5/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment5"/>
              </ns2:Segment5>
            </xsl:if>
            <xsl:if test="ns0:Segment6">
              <ns2:Segment6>
                <xsl:if test="ns0:Segment6/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment6/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment6"/>
              </ns2:Segment6>
            </xsl:if>
            <xsl:if test="ns0:Segment7">
              <ns2:Segment7>
                <xsl:if test="ns0:Segment7/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment7/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment7"/>
              </ns2:Segment7>
            </xsl:if>
            <xsl:if test="ns0:Segment8">
              <ns2:Segment8>
                <xsl:if test="ns0:Segment8/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment8/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment8"/>
              </ns2:Segment8>
            </xsl:if>
            <xsl:if test="ns0:Segment9">
              <ns2:Segment9>
                <xsl:if test="ns0:Segment9/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment9/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment9"/>
              </ns2:Segment9>
            </xsl:if>
            <xsl:if test="ns0:Segment10">
              <ns2:Segment10>
                <xsl:if test="ns0:Segment10/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment10/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment10"/>
              </ns2:Segment10>
            </xsl:if>
            <xsl:if test="ns0:Segment11">
              <ns2:Segment11>
                <xsl:if test="ns0:Segment11/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment11/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment11"/>
              </ns2:Segment11>
            </xsl:if>
            <xsl:if test="ns0:Segment12">
              <ns2:Segment12>
                <xsl:if test="ns0:Segment12/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment12/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment12"/>
              </ns2:Segment12>
            </xsl:if>
            <xsl:if test="ns0:Segment13">
              <ns2:Segment13>
                <xsl:if test="ns0:Segment13/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment13/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment13"/>
              </ns2:Segment13>
            </xsl:if>
            <xsl:if test="ns0:Segment14">
              <ns2:Segment14>
                <xsl:if test="ns0:Segment14/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment14/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment14"/>
              </ns2:Segment14>
            </xsl:if>
            <xsl:if test="ns0:Segment15">
              <ns2:Segment15>
                <xsl:if test="ns0:Segment15/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment15/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment15"/>
              </ns2:Segment15>
            </xsl:if>
            <xsl:if test="ns0:Segment16">
              <ns2:Segment16>
                <xsl:if test="ns0:Segment16/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment16/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment16"/>
              </ns2:Segment16>
            </xsl:if>
            <xsl:if test="ns0:Segment17">
              <ns2:Segment17>
                <xsl:if test="ns0:Segment17/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment17/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment17"/>
              </ns2:Segment17>
            </xsl:if>
            <xsl:if test="ns0:Segment18">
              <ns2:Segment18>
                <xsl:if test="ns0:Segment18/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment18/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment18"/>
              </ns2:Segment18>
            </xsl:if>
            <xsl:if test="ns0:Segment19">
              <ns2:Segment19>
                <xsl:if test="ns0:Segment19/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment19/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment19"/>
              </ns2:Segment19>
            </xsl:if>
            <xsl:if test="ns0:Segment20">
              <ns2:Segment20>
                <xsl:if test="ns0:Segment20/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment20/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment20"/>
              </ns2:Segment20>
            </xsl:if>
            <xsl:if test="ns0:Segment21">
              <ns2:Segment21>
                <xsl:if test="ns0:Segment21/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment21/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment21"/>
              </ns2:Segment21>
            </xsl:if>
            <xsl:if test="ns0:Segment22">
              <ns2:Segment22>
                <xsl:if test="ns0:Segment22/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment22/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment22"/>
              </ns2:Segment22>
            </xsl:if>
            <xsl:if test="ns0:Segment23">
              <ns2:Segment23>
                <xsl:if test="ns0:Segment23/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment23/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment23"/>
              </ns2:Segment23>
            </xsl:if>
            <xsl:if test="ns0:Segment24">
              <ns2:Segment24>
                <xsl:if test="ns0:Segment24/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment24/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment24"/>
              </ns2:Segment24>
            </xsl:if>
            <xsl:if test="ns0:Segment25">
              <ns2:Segment25>
                <xsl:if test="ns0:Segment25/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment25/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment25"/>
              </ns2:Segment25>
            </xsl:if>
            <xsl:if test="ns0:Segment26">
              <ns2:Segment26>
                <xsl:if test="ns0:Segment26/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment26/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment26"/>
              </ns2:Segment26>
            </xsl:if>
            <xsl:if test="ns0:Segment27">
              <ns2:Segment27>
                <xsl:if test="ns0:Segment27/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment27/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment27"/>
              </ns2:Segment27>
            </xsl:if>
            <xsl:if test="ns0:Segment28">
              <ns2:Segment28>
                <xsl:if test="ns0:Segment28/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment28/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment28"/>
              </ns2:Segment28>
            </xsl:if>
            <xsl:if test="ns0:Segment29">
              <ns2:Segment29>
                <xsl:if test="ns0:Segment29/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment29/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment29"/>
              </ns2:Segment29>
            </xsl:if>
            <xsl:if test="ns0:Segment30">
              <ns2:Segment30>
                <xsl:if test="ns0:Segment30/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Segment30/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Segment30"/>
              </ns2:Segment30>
            </xsl:if>
            <xsl:if test="ns0:CurrencyCode">
              <ns2:CurrencyCode>
                <xsl:value-of select="ns0:CurrencyCode"/>
              </ns2:CurrencyCode>
            </xsl:if>
            <xsl:if test="ns0:EnteredCrAmount">
              <ns2:EnteredCrAmount>
                <xsl:if test="ns0:EnteredCrAmount/@currencyCode">
                  <xsl:attribute name="currencyCode">
                    <xsl:value-of select="ns0:EnteredCrAmount/@currencyCode"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns0:EnteredCrAmount/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:EnteredCrAmount/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:EnteredCrAmount"/>
              </ns2:EnteredCrAmount>
            </xsl:if>
            <xsl:if test="ns0:EnteredDrAmount">
              <ns2:EnteredDrAmount>
                <xsl:if test="ns0:EnteredDrAmount/@currencyCode">
                  <xsl:attribute name="currencyCode">
                    <xsl:value-of select="ns0:EnteredDrAmount/@currencyCode"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:if test="ns0:EnteredDrAmount/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:EnteredDrAmount/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:EnteredDrAmount"/>
              </ns2:EnteredDrAmount>
            </xsl:if>
            <xsl:if test="ns0:AccountedCr">
              <ns2:AccountedCr>
                <xsl:if test="ns0:AccountedCr/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AccountedCr/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AccountedCr"/>
              </ns2:AccountedCr>
            </xsl:if>
            <xsl:if test="ns0:AccountedDr">
              <ns2:AccountedDr>
                <xsl:if test="ns0:AccountedDr/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AccountedDr/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AccountedDr"/>
              </ns2:AccountedDr>
            </xsl:if>
            <xsl:if test="ns0:StatisticalValue">
              <ns2:StatisticalValue>
                <xsl:if test="ns0:StatisticalValue/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:StatisticalValue/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:StatisticalValue"/>
              </ns2:StatisticalValue>
            </xsl:if>
            <xsl:if test="ns0:UserCurrencyConversionType">
              <ns2:UserCurrencyConversionType>
                <xsl:if test="ns0:UserCurrencyConversionType/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:UserCurrencyConversionType/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:UserCurrencyConversionType"/>
              </ns2:UserCurrencyConversionType>
            </xsl:if>
            <xsl:if test="ns0:CurrencyConversionDate">
              <ns2:CurrencyConversionDate>
                <xsl:if test="ns0:CurrencyConversionDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:CurrencyConversionDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:CurrencyConversionDate"/>
              </ns2:CurrencyConversionDate>
            </xsl:if>
            <xsl:if test="ns0:CurrencyConversionRate">
              <ns2:CurrencyConversionRate>
                <xsl:if test="ns0:CurrencyConversionRate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:CurrencyConversionRate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:CurrencyConversionRate"/>
              </ns2:CurrencyConversionRate>
            </xsl:if>
            <xsl:if test="ns0:CurrencyConversionType">
              <ns2:CurrencyConversionType>
                <xsl:if test="ns0:CurrencyConversionType/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:CurrencyConversionType/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:CurrencyConversionType"/>
              </ns2:CurrencyConversionType>
            </xsl:if>
            <xsl:if test="ns0:Reference1">
              <ns2:Reference1>
                <xsl:if test="ns0:Reference1/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference1/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference1"/>
              </ns2:Reference1>
            </xsl:if>
            <xsl:if test="ns0:Reference2">
              <ns2:Reference2>
                <xsl:if test="ns0:Reference2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference2"/>
              </ns2:Reference2>
            </xsl:if>
            <xsl:if test="ns0:Reference3">
              <ns2:Reference3>
                <xsl:if test="ns0:Reference3/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference3/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference3"/>
              </ns2:Reference3>
            </xsl:if>
            <xsl:if test="ns0:Reference6">
              <ns2:Reference6>
                <xsl:if test="ns0:Reference6/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference6/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference6"/>
              </ns2:Reference6>
            </xsl:if>
            <xsl:if test="ns0:Reference7">
              <ns2:Reference7>
                <xsl:if test="ns0:Reference7/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference7/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference7"/>
              </ns2:Reference7>
            </xsl:if>
            <xsl:if test="ns0:Reference8">
              <ns2:Reference8>
                <xsl:if test="ns0:Reference8/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference8/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference8"/>
              </ns2:Reference8>
            </xsl:if>
            <xsl:if test="ns0:Reference9">
              <ns2:Reference9>
                <xsl:if test="ns0:Reference9/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference9/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference9"/>
              </ns2:Reference9>
            </xsl:if>
            <ns2:Reference10>
              <xsl:value-of select="concat(/ns0:CrearACRequest/ns0:BatchDescription, ' ' , /ns0:CrearACRequest/ns0:AccountingPeriodName)" />
            </ns2:Reference10>
            <xsl:if test="ns0:Reference11">
              <ns2:Reference11>
                <xsl:if test="ns0:Reference11/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference11/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference11"/>
              </ns2:Reference11>
            </xsl:if>
            <xsl:if test="ns0:Reference12">
              <ns2:Reference12>
                <xsl:if test="ns0:Reference12/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference12/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference12"/>
              </ns2:Reference12>
            </xsl:if>
            <xsl:if test="ns0:Reference13">
              <ns2:Reference13>
                <xsl:if test="ns0:Reference13/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference13/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference13"/>
              </ns2:Reference13>
            </xsl:if>
            <xsl:if test="ns0:Reference14">
              <ns2:Reference14>
                <xsl:if test="ns0:Reference14/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference14/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference14"/>
              </ns2:Reference14>
            </xsl:if>
            <xsl:if test="ns0:Reference15">
              <ns2:Reference15>
                <xsl:if test="ns0:Reference15/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference15/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference15"/>
              </ns2:Reference15>
            </xsl:if>
            <xsl:if test="ns0:Reference16">
              <ns2:Reference16>
                <xsl:if test="ns0:Reference16/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference16/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference16"/>
              </ns2:Reference16>
            </xsl:if>
            <xsl:if test="ns0:Reference17">
              <ns2:Reference17>
                <xsl:if test="ns0:Reference17/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference17/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference17"/>
              </ns2:Reference17>
            </xsl:if>
            <xsl:if test="ns0:Reference18">
              <ns2:Reference18>
                <xsl:if test="ns0:Reference18/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference18/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference18"/>
              </ns2:Reference18>
            </xsl:if>
            <xsl:if test="ns0:Reference19">
              <ns2:Reference19>
                <xsl:if test="ns0:Reference19/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference19/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference19"/>
              </ns2:Reference19>
            </xsl:if>
            <xsl:if test="ns0:Reference20">
              <ns2:Reference20>
                <xsl:if test="ns0:Reference20/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference20/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference20"/>
              </ns2:Reference20>
            </xsl:if>
            <xsl:if test="ns0:Reference21">
              <ns2:Reference21>
                <xsl:if test="ns0:Reference21/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference21/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference21"/>
              </ns2:Reference21>
            </xsl:if>
            <xsl:if test="ns0:Reference22">
              <ns2:Reference22>
                <xsl:if test="ns0:Reference22/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference22/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference22"/>
              </ns2:Reference22>
            </xsl:if>
            <xsl:if test="ns0:Reference23">
              <ns2:Reference23>
                <xsl:if test="ns0:Reference23/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference23/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference23"/>
              </ns2:Reference23>
            </xsl:if>
            <xsl:if test="ns0:Reference24">
              <ns2:Reference24>
                <xsl:if test="ns0:Reference24/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference24/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference24"/>
              </ns2:Reference24>
            </xsl:if>
            <xsl:if test="ns0:Reference25">
              <ns2:Reference25>
                <xsl:if test="ns0:Reference25/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference25/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference25"/>
              </ns2:Reference25>
            </xsl:if>
            <xsl:if test="ns0:Reference26">
              <ns2:Reference26>
                <xsl:if test="ns0:Reference26/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference26/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference26"/>
              </ns2:Reference26>
            </xsl:if>
            <xsl:if test="ns0:Reference27">
              <ns2:Reference27>
                <xsl:if test="ns0:Reference27/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference27/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference27"/>
              </ns2:Reference27>
            </xsl:if>
            <xsl:if test="ns0:Reference28">
              <ns2:Reference28>
                <xsl:if test="ns0:Reference28/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference28/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference28"/>
              </ns2:Reference28>
            </xsl:if>
            <xsl:if test="ns0:Reference29">
              <ns2:Reference29>
                <xsl:if test="ns0:Reference29/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference29/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference29"/>
              </ns2:Reference29>
            </xsl:if>
            <xsl:if test="ns0:Reference30">
              <ns2:Reference30>
                <xsl:if test="ns0:Reference30/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Reference30/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Reference30"/>
              </ns2:Reference30>
            </xsl:if>
            <xsl:if test="ns0:ReferenceDate">
              <ns2:ReferenceDate>
                <xsl:if test="ns0:ReferenceDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:ReferenceDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:ReferenceDate"/>
              </ns2:ReferenceDate>
            </xsl:if>
            <xsl:if test="ns0:Attribute1">
              <ns2:Attribute1>
                <xsl:if test="ns0:Attribute1/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute1/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute1"/>
              </ns2:Attribute1>
            </xsl:if>
            <xsl:if test="ns0:Attribute2">
              <ns2:Attribute2>
                <xsl:if test="ns0:Attribute2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute2"/>
              </ns2:Attribute2>
            </xsl:if>
            <xsl:if test="ns0:Attribute3">
              <ns2:Attribute3>
                <xsl:if test="ns0:Attribute3/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute3/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute3"/>
              </ns2:Attribute3>
            </xsl:if>
            <xsl:if test="ns0:Attribute4">
              <ns2:Attribute4>
                <xsl:if test="ns0:Attribute4/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute4/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute4"/>
              </ns2:Attribute4>
            </xsl:if>
            <xsl:if test="ns0:Attribute5">
              <ns2:Attribute5>
                <xsl:if test="ns0:Attribute5/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute5/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute5"/>
              </ns2:Attribute5>
            </xsl:if>
            <xsl:if test="ns0:Attribute6">
              <ns2:Attribute6>
                <xsl:if test="ns0:Attribute6/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute6/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute6"/>
              </ns2:Attribute6>
            </xsl:if>
            <xsl:if test="ns0:Attribute7">
              <ns2:Attribute7>
                <xsl:if test="ns0:Attribute7/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute7/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute7"/>
              </ns2:Attribute7>
            </xsl:if>
            <xsl:if test="ns0:Attribute8">
              <ns2:Attribute8>
                <xsl:if test="ns0:Attribute8/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute8/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute8"/>
              </ns2:Attribute8>
            </xsl:if>
            <xsl:if test="ns0:Attribute9">
              <ns2:Attribute9>
                <xsl:if test="ns0:Attribute9/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute9/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute9"/>
              </ns2:Attribute9>
            </xsl:if>
            <xsl:if test="ns0:Attribute10">
              <ns2:Attribute10>
                <xsl:if test="ns0:Attribute10/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute10/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute10"/>
              </ns2:Attribute10>
            </xsl:if>
            <xsl:if test="ns0:Attribute11">
              <ns2:Attribute11>
                <xsl:if test="ns0:Attribute11/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute11/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute11"/>
              </ns2:Attribute11>
            </xsl:if>
            <xsl:if test="ns0:Attribute12">
              <ns2:Attribute12>
                <xsl:if test="ns0:Attribute12/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute12/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute12"/>
              </ns2:Attribute12>
            </xsl:if>
            <xsl:if test="ns0:Attribute13">
              <ns2:Attribute13>
                <xsl:if test="ns0:Attribute13/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute13/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute13"/>
              </ns2:Attribute13>
            </xsl:if>
            <xsl:if test="ns0:Attribute14">
              <ns2:Attribute14>
                <xsl:if test="ns0:Attribute14/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute14/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute14"/>
              </ns2:Attribute14>
            </xsl:if>
            <xsl:if test="ns0:Attribute15">
              <ns2:Attribute15>
                <xsl:if test="ns0:Attribute15/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute15/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute15"/>
              </ns2:Attribute15>
            </xsl:if>
            <xsl:if test="ns0:Attribute16">
              <ns2:Attribute16>
                <xsl:if test="ns0:Attribute16/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute16/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute16"/>
              </ns2:Attribute16>
            </xsl:if>
            <xsl:if test="ns0:Attribute17">
              <ns2:Attribute17>
                <xsl:if test="ns0:Attribute17/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute17/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute17"/>
              </ns2:Attribute17>
            </xsl:if>
            <xsl:if test="ns0:Attribute18">
              <ns2:Attribute18>
                <xsl:if test="ns0:Attribute18/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute18/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute18"/>
              </ns2:Attribute18>
            </xsl:if>
            <xsl:if test="ns0:Attribute19">
              <ns2:Attribute19>
                <xsl:if test="ns0:Attribute19/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute19/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute19"/>
              </ns2:Attribute19>
            </xsl:if>
            <xsl:if test="ns0:Attribute20">
              <ns2:Attribute20>
                <xsl:if test="ns0:Attribute20/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:Attribute20/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:Attribute20"/>
              </ns2:Attribute20>
            </xsl:if>
            <xsl:if test="ns0:AttributeCategory">
              <ns2:AttributeCategory>
                <xsl:if test="ns0:AttributeCategory/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AttributeCategory/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AttributeCategory"/>
              </ns2:AttributeCategory>
            </xsl:if>
            <xsl:if test="ns0:AttributeCategory2">
              <ns2:AttributeCategory2>
                <xsl:if test="ns0:AttributeCategory2/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AttributeCategory2/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AttributeCategory2"/>
              </ns2:AttributeCategory2>
            </xsl:if>
            <xsl:if test="ns0:AttributeCategory3">
              <ns2:AttributeCategory3>
                <xsl:if test="ns0:AttributeCategory3/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AttributeCategory3/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AttributeCategory3"/>
              </ns2:AttributeCategory3>
            </xsl:if>
            <xsl:if test="ns0:AverageJournalFlag">
              <ns2:AverageJournalFlag>
                <xsl:if test="ns0:AverageJournalFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:AverageJournalFlag/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:AverageJournalFlag"/>
              </ns2:AverageJournalFlag>
            </xsl:if>
            <xsl:if test="ns0:BalancingSegmentValue">
              <ns2:BalancingSegmentValue>
                <xsl:if test="ns0:BalancingSegmentValue/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:BalancingSegmentValue/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:BalancingSegmentValue"/>
              </ns2:BalancingSegmentValue>
            </xsl:if>
            <xsl:if test="ns0:DescrFlexErrorMessage">
              <ns2:DescrFlexErrorMessage>
                <xsl:if test="ns0:DescrFlexErrorMessage/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:DescrFlexErrorMessage/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:DescrFlexErrorMessage"/>
              </ns2:DescrFlexErrorMessage>
            </xsl:if>
            <xsl:if test="ns0:GlSlLinkId">
              <ns2:GlSlLinkId>
                <xsl:if test="ns0:GlSlLinkId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:GlSlLinkId/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:GlSlLinkId"/>
              </ns2:GlSlLinkId>
            </xsl:if>
            <xsl:if test="ns0:GlSlLinkTable">
              <ns2:GlSlLinkTable>
                <xsl:if test="ns0:GlSlLinkTable/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:GlSlLinkTable/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:GlSlLinkTable"/>
              </ns2:GlSlLinkTable>
            </xsl:if>
            <xsl:if test="ns0:InvoiceAmount">
              <ns2:InvoiceAmount>
                <xsl:if test="ns0:InvoiceAmount/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:InvoiceAmount/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:InvoiceAmount"/>
              </ns2:InvoiceAmount>
            </xsl:if>
            <xsl:if test="ns0:InvoiceDate">
              <ns2:InvoiceDate>
                <xsl:if test="ns0:InvoiceDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:InvoiceDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:InvoiceDate"/>
              </ns2:InvoiceDate>
            </xsl:if>
            <xsl:if test="ns0:InvoiceIdentifier">
              <ns2:InvoiceIdentifier>
                <xsl:if test="ns0:InvoiceIdentifier/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:InvoiceIdentifier/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:InvoiceIdentifier"/>
              </ns2:InvoiceIdentifier>
            </xsl:if>
            <xsl:choose>
              <xsl:when test="not(/ns0:JeCategoryName)">
                <ns2:JeCategoryName>Manual</ns2:JeCategoryName>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:JeCategoryName">
                  <ns2:JeCategoryName>
                    <xsl:if test="ns0:JeCategoryName/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:JeCategoryName/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:JeCategoryName"/>
                  </ns2:JeCategoryName>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:choose>
              <xsl:when test="not(/ns0:JeSourceName)">
                <ns2:JeSourceName>Manual</ns2:JeSourceName>
              </xsl:when>
              <xsl:otherwise>
                <xsl:if test="ns0:JeSourceName">
                  <ns2:JeSourceName>
                    <xsl:if test="ns0:JeSourceName/@xsi:nil">
                      <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                        <xsl:value-of select="ns0:JeSourceName/@xsi:nil"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="ns0:JeSourceName"/>
                  </ns2:JeSourceName>
                </xsl:if>
              </xsl:otherwise>
            </xsl:choose>
            <xsl:if test="ns0:JgzzReconReference">
              <ns2:JgzzReconReference>
                <xsl:if test="ns0:JgzzReconReference/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:JgzzReconReference/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:JgzzReconReference"/>
              </ns2:JgzzReconReference>
            </xsl:if>
            <xsl:if test="ns0:ManagementSegmentValue">
              <ns2:ManagementSegmentValue>
                <xsl:if test="ns0:ManagementSegmentValue/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:ManagementSegmentValue/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:ManagementSegmentValue"/>
              </ns2:ManagementSegmentValue>
            </xsl:if>
            <xsl:if test="ns0:ObjectVersionNumber">
              <ns2:ObjectVersionNumber>
                <xsl:value-of select="ns0:ObjectVersionNumber"/>
              </ns2:ObjectVersionNumber>
            </xsl:if>
            <xsl:if test="ns0:OriginatingBalSegValue">
              <ns2:OriginatingBalSegValue>
                <xsl:if test="ns0:OriginatingBalSegValue/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:OriginatingBalSegValue/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:OriginatingBalSegValue"/>
              </ns2:OriginatingBalSegValue>
            </xsl:if>
            <xsl:if test="ns0:SetOfBooksId">
              <ns2:SetOfBooksId>
                <xsl:if test="ns0:SetOfBooksId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:SetOfBooksId/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:SetOfBooksId"/>
              </ns2:SetOfBooksId>
            </xsl:if>
            <xsl:if test="ns0:Status">
              <ns2:Status>
                <xsl:value-of select="ns0:Status"/>
              </ns2:Status>
            </xsl:if>
            <xsl:if test="ns0:TaxCode">
              <ns2:TaxCode>
                <xsl:if test="ns0:TaxCode/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:TaxCode/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:TaxCode"/>
              </ns2:TaxCode>
            </xsl:if>
            <xsl:if test="ns0:TransactionDate">
              <ns2:TransactionDate>
                <xsl:if test="ns0:TransactionDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:TransactionDate"/>
              </ns2:TransactionDate>
            </xsl:if>
            <xsl:if test="ns0:USSGLTransactionCode">
              <ns2:USSGLTransactionCode>
                <xsl:if test="ns0:USSGLTransactionCode/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:USSGLTransactionCode/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:USSGLTransactionCode"/>
              </ns2:USSGLTransactionCode>
            </xsl:if>
            <xsl:if test="ns0:GlInterfaceId">
              <ns2:GlInterfaceId>
                <xsl:if test="ns0:GlInterfaceId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:GlInterfaceId/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:GlInterfaceId"/>
              </ns2:GlInterfaceId>
            </xsl:if>
            <xsl:if test="ns0:LegalEntityIdentifier">
              <ns2:LegalEntityIdentifier>
                <xsl:if test="ns0:LegalEntityIdentifier/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:LegalEntityIdentifier/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:LegalEntityIdentifier"/>
              </ns2:LegalEntityIdentifier>
            </xsl:if>
            <xsl:if test="ns0:LedgerName">
              <ns2:LedgerName>
                <xsl:if test="ns0:LedgerName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:LedgerName/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:LedgerName"/>
              </ns2:LedgerName>
            </xsl:if>
          </ns2:GlInterface>
        </xsl:for-each>
      </tns:interfaceRows>
    </tns:importJournals>
  </xsl:template>
</xsl:stylesheet>
