<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns0="http://www.dpworld.com/I004_CrearACBatch/CrearACBatch" xmlns:tns="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/jms/SOA_DPWORLD/I004_CrearACBatchJms/jmsService"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/jmsService.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CrearACBatchRequest" namespace="http://www.dpworld.com/I004_CrearACBatch/CrearACBatch"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://localhost:7101/soa-infra/services/default/I001_SCACrearAC!1.0/WSDL_SCA/CrearAsientoContable.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CrearACRequest" namespace="http://www.dpworld.com/SOA_DPWORLD/I001CrearAsientoContable"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [SUN NOV 18 21:00:55 ECT 2018].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <tns:CrearACRequest>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag">
            <tns:flag>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag"/>
            </tns:flag>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchName">
            <tns:BatchName>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchName/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchName"/>
            </tns:BatchName>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchDescription">
            <tns:BatchDescription>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:BatchDescription/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchDescription/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:BatchDescription"/>
            </tns:BatchDescription>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:LedgerId">
            <tns:LedgerId>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:LedgerId/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:LedgerId/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:LedgerId"/>
            </tns:LedgerId>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName">
            <tns:AccountingPeriodName>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingPeriodName"/>
            </tns:AccountingPeriodName>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingDate">
            <tns:AccountingDate>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:AccountingDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingDate/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:AccountingDate"/>
            </tns:AccountingDate>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserSourceName">
            <tns:UserSourceName>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserSourceName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserSourceName/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserSourceName"/>
            </tns:UserSourceName>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserCategoryName">
            <tns:UserCategoryName>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:UserCategoryName/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserCategoryName/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:UserCategoryName"/>
            </tns:UserCategoryName>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag">
            <tns:ErrorToSuspenseFlag>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ErrorToSuspenseFlag"/>
            </tns:ErrorToSuspenseFlag>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:SummaryFlag">
            <tns:SummaryFlag>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:SummaryFlag/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:SummaryFlag/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:SummaryFlag"/>
            </tns:SummaryFlag>
         </xsl:if>
         <xsl:if test="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField">
            <tns:ImportDescriptiveFlexField>
               <xsl:if test="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                     <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField/@xsi:nil"/>
                  </xsl:attribute>
               </xsl:if>
               <xsl:value-of select="/ns0:CrearACBatchRequest/ns0:ImportDescriptiveFlexField"/>
            </tns:ImportDescriptiveFlexField>
         </xsl:if>
         <xsl:for-each select="/ns0:CrearACBatchRequest/ns0:GlInterface">
            <tns:GlInterface>
               <xsl:if test="ns0:LedgerId">
                  <tns:LedgerId>
                     <xsl:value-of select="ns0:LedgerId"/>
                  </tns:LedgerId>
               </xsl:if>
               <xsl:if test="ns0:PeriodName">
                  <tns:PeriodName>
                     <xsl:if test="ns0:PeriodName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:PeriodName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:PeriodName"/>
                  </tns:PeriodName>
               </xsl:if>
               <xsl:if test="ns0:AccountingDate">
                  <tns:AccountingDate>
                     <xsl:value-of select="ns0:AccountingDate"/>
                  </tns:AccountingDate>
               </xsl:if>
               <xsl:if test="ns0:UserJeSourceName">
                  <tns:UserJeSourceName>
                     <xsl:value-of select="ns0:UserJeSourceName"/>
                  </tns:UserJeSourceName>
               </xsl:if>
               <xsl:if test="ns0:UserJeCategoryName">
                  <tns:UserJeCategoryName>
                     <xsl:value-of select="ns0:UserJeCategoryName"/>
                  </tns:UserJeCategoryName>
               </xsl:if>
               <xsl:if test="ns0:GroupId">
                  <tns:GroupId>
                     <xsl:value-of select="ns0:GroupId"/>
                  </tns:GroupId>
               </xsl:if>
               <xsl:if test="ns0:ChartOfAccountsId">
                  <tns:ChartOfAccountsId>
                     <xsl:if test="ns0:ChartOfAccountsId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ChartOfAccountsId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ChartOfAccountsId"/>
                  </tns:ChartOfAccountsId>
               </xsl:if>
               <xsl:if test="ns0:BalanceType">
                  <tns:BalanceType>
                     <xsl:value-of select="ns0:BalanceType"/>
                  </tns:BalanceType>
               </xsl:if>
               <tns:CodeCombinationId/>
               <tns:Segment1/>
               <xsl:if test="ns0:AccountedCr">
                  <tns:AccountedCr>
                     <xsl:if test="ns0:AccountedCr/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AccountedCr/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AccountedCr"/>
                  </tns:AccountedCr>
               </xsl:if>
               <xsl:if test="ns0:AccountedDr">
                  <tns:AccountedDr>
                     <xsl:if test="ns0:AccountedDr/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AccountedDr/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AccountedDr"/>
                  </tns:AccountedDr>
               </xsl:if>
               <xsl:if test="ns0:StatisticalValue">
                  <tns:StatisticalValue>
                     <xsl:if test="ns0:StatisticalValue/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:StatisticalValue/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:StatisticalValue"/>
                  </tns:StatisticalValue>
               </xsl:if>
               <xsl:if test="ns0:UserCurrencyConversionType">
                  <tns:UserCurrencyConversionType>
                     <xsl:if test="ns0:UserCurrencyConversionType/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:UserCurrencyConversionType/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:UserCurrencyConversionType"/>
                  </tns:UserCurrencyConversionType>
               </xsl:if>
               <xsl:if test="ns0:CurrencyConversionDate">
                  <tns:CurrencyConversionDate>
                     <xsl:if test="ns0:CurrencyConversionDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CurrencyConversionDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CurrencyConversionDate"/>
                  </tns:CurrencyConversionDate>
               </xsl:if>
               <xsl:if test="ns0:CurrencyConversionRate">
                  <tns:CurrencyConversionRate>
                     <xsl:if test="ns0:CurrencyConversionRate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CurrencyConversionRate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CurrencyConversionRate"/>
                  </tns:CurrencyConversionRate>
               </xsl:if>
               <xsl:if test="ns0:CurrencyConversionType">
                  <tns:CurrencyConversionType>
                     <xsl:if test="ns0:CurrencyConversionType/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:CurrencyConversionType/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:CurrencyConversionType"/>
                  </tns:CurrencyConversionType>
               </xsl:if>
               <xsl:if test="ns0:Reference1">
                  <tns:Reference1>
                     <xsl:if test="ns0:Reference1/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference1/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference1"/>
                  </tns:Reference1>
               </xsl:if>
               <xsl:if test="ns0:Reference2">
                  <tns:Reference2>
                     <xsl:if test="ns0:Reference2/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference2/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference2"/>
                  </tns:Reference2>
               </xsl:if>
               <xsl:if test="ns0:Reference3">
                  <tns:Reference3>
                     <xsl:if test="ns0:Reference3/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference3/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference3"/>
                  </tns:Reference3>
               </xsl:if>
               <xsl:if test="ns0:Reference6">
                  <tns:Reference6>
                     <xsl:if test="ns0:Reference6/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference6/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference6"/>
                  </tns:Reference6>
               </xsl:if>
               <xsl:if test="ns0:Reference7">
                  <tns:Reference7>
                     <xsl:if test="ns0:Reference7/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference7/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference7"/>
                  </tns:Reference7>
               </xsl:if>
               <xsl:if test="ns0:Reference8">
                  <tns:Reference8>
                     <xsl:if test="ns0:Reference8/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference8/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference8"/>
                  </tns:Reference8>
               </xsl:if>
               <xsl:if test="ns0:Reference9">
                  <tns:Reference9>
                     <xsl:if test="ns0:Reference9/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference9/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference9"/>
                  </tns:Reference9>
               </xsl:if>
               <xsl:if test="ns0:Reference10">
                  <tns:Reference10>
                     <xsl:if test="ns0:Reference10/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference10/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference10"/>
                  </tns:Reference10>
               </xsl:if>
               <xsl:if test="ns0:Reference11">
                  <tns:Reference11>
                     <xsl:if test="ns0:Reference11/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference11/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference11"/>
                  </tns:Reference11>
               </xsl:if>
               <xsl:if test="ns0:Reference12">
                  <tns:Reference12>
                     <xsl:if test="ns0:Reference12/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference12/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference12"/>
                  </tns:Reference12>
               </xsl:if>
               <xsl:if test="ns0:Reference13">
                  <tns:Reference13>
                     <xsl:if test="ns0:Reference13/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference13/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference13"/>
                  </tns:Reference13>
               </xsl:if>
               <xsl:if test="ns0:Reference14">
                  <tns:Reference14>
                     <xsl:if test="ns0:Reference14/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference14/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference14"/>
                  </tns:Reference14>
               </xsl:if>
               <xsl:if test="ns0:Reference15">
                  <tns:Reference15>
                     <xsl:if test="ns0:Reference15/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference15/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference15"/>
                  </tns:Reference15>
               </xsl:if>
               <xsl:if test="ns0:Reference16">
                  <tns:Reference16>
                     <xsl:if test="ns0:Reference16/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference16/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference16"/>
                  </tns:Reference16>
               </xsl:if>
               <xsl:if test="ns0:Reference17">
                  <tns:Reference17>
                     <xsl:if test="ns0:Reference17/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference17/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference17"/>
                  </tns:Reference17>
               </xsl:if>
               <xsl:if test="ns0:Reference18">
                  <tns:Reference18>
                     <xsl:if test="ns0:Reference18/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference18/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference18"/>
                  </tns:Reference18>
               </xsl:if>
               <xsl:if test="ns0:Reference19">
                  <tns:Reference19>
                     <xsl:if test="ns0:Reference19/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference19/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference19"/>
                  </tns:Reference19>
               </xsl:if>
               <xsl:if test="ns0:Reference20">
                  <tns:Reference20>
                     <xsl:if test="ns0:Reference20/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference20/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference20"/>
                  </tns:Reference20>
               </xsl:if>
               <xsl:if test="ns0:Reference21">
                  <tns:Reference21>
                     <xsl:if test="ns0:Reference21/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference21/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference21"/>
                  </tns:Reference21>
               </xsl:if>
               <xsl:if test="ns0:Reference22">
                  <tns:Reference22>
                     <xsl:if test="ns0:Reference22/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference22/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference22"/>
                  </tns:Reference22>
               </xsl:if>
               <xsl:if test="ns0:Reference23">
                  <tns:Reference23>
                     <xsl:if test="ns0:Reference23/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference23/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference23"/>
                  </tns:Reference23>
               </xsl:if>
               <xsl:if test="ns0:Reference24">
                  <tns:Reference24>
                     <xsl:if test="ns0:Reference24/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference24/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference24"/>
                  </tns:Reference24>
               </xsl:if>
               <xsl:if test="ns0:Reference25">
                  <tns:Reference25>
                     <xsl:if test="ns0:Reference25/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference25/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference25"/>
                  </tns:Reference25>
               </xsl:if>
               <xsl:if test="ns0:Reference26">
                  <tns:Reference26>
                     <xsl:if test="ns0:Reference26/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference26/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference26"/>
                  </tns:Reference26>
               </xsl:if>
               <xsl:if test="ns0:Reference27">
                  <tns:Reference27>
                     <xsl:if test="ns0:Reference27/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference27/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference27"/>
                  </tns:Reference27>
               </xsl:if>
               <xsl:if test="ns0:Reference28">
                  <tns:Reference28>
                     <xsl:if test="ns0:Reference28/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference28/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference28"/>
                  </tns:Reference28>
               </xsl:if>
               <xsl:if test="ns0:Reference29">
                  <tns:Reference29>
                     <xsl:if test="ns0:Reference29/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference29/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference29"/>
                  </tns:Reference29>
               </xsl:if>
               <xsl:if test="ns0:Reference30">
                  <tns:Reference30>
                     <xsl:if test="ns0:Reference30/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:Reference30/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:Reference30"/>
                  </tns:Reference30>
               </xsl:if>
               <xsl:if test="ns0:ReferenceDate">
                  <tns:ReferenceDate>
                     <xsl:if test="ns0:ReferenceDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ReferenceDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ReferenceDate"/>
                  </tns:ReferenceDate>
               </xsl:if>
               <xsl:if test="ns0:AttributeCategory">
                  <tns:AttributeCategory>
                     <xsl:if test="ns0:AttributeCategory/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AttributeCategory/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AttributeCategory"/>
                  </tns:AttributeCategory>
               </xsl:if>
               <xsl:if test="ns0:AttributeCategory2">
                  <tns:AttributeCategory2>
                     <xsl:if test="ns0:AttributeCategory2/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AttributeCategory2/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AttributeCategory2"/>
                  </tns:AttributeCategory2>
               </xsl:if>
               <xsl:if test="ns0:AttributeCategory3">
                  <tns:AttributeCategory3>
                     <xsl:if test="ns0:AttributeCategory3/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:AttributeCategory3/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:AttributeCategory3"/>
                  </tns:AttributeCategory3>
               </xsl:if>
               <xsl:if test="ns0:BalancingSegmentValue">
                  <tns:BalancingSegmentValue>
                     <xsl:if test="ns0:BalancingSegmentValue/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:BalancingSegmentValue/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:BalancingSegmentValue"/>
                  </tns:BalancingSegmentValue>
               </xsl:if>
               <xsl:if test="ns0:DescrFlexErrorMessage">
                  <tns:DescrFlexErrorMessage>
                     <xsl:if test="ns0:DescrFlexErrorMessage/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:DescrFlexErrorMessage/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:DescrFlexErrorMessage"/>
                  </tns:DescrFlexErrorMessage>
               </xsl:if>
               <xsl:if test="ns0:GlSlLinkId">
                  <tns:GlSlLinkId>
                     <xsl:if test="ns0:GlSlLinkId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:GlSlLinkId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:GlSlLinkId"/>
                  </tns:GlSlLinkId>
               </xsl:if>
               <xsl:if test="ns0:GlSlLinkTable">
                  <tns:GlSlLinkTable>
                     <xsl:if test="ns0:GlSlLinkTable/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:GlSlLinkTable/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:GlSlLinkTable"/>
                  </tns:GlSlLinkTable>
               </xsl:if>
               <xsl:if test="ns0:JeCategoryName">
                  <tns:JeCategoryName>
                     <xsl:if test="ns0:JeCategoryName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:JeCategoryName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:JeCategoryName"/>
                  </tns:JeCategoryName>
               </xsl:if>
               <xsl:if test="ns0:JeSourceName">
                  <tns:JeSourceName>
                     <xsl:if test="ns0:JeSourceName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:JeSourceName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:JeSourceName"/>
                  </tns:JeSourceName>
               </xsl:if>
               <xsl:if test="ns0:JgzzReconReference">
                  <tns:JgzzReconReference>
                     <xsl:if test="ns0:JgzzReconReference/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:JgzzReconReference/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:JgzzReconReference"/>
                  </tns:JgzzReconReference>
               </xsl:if>
               <xsl:if test="ns0:ManagementSegmentValue">
                  <tns:ManagementSegmentValue>
                     <xsl:if test="ns0:ManagementSegmentValue/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:ManagementSegmentValue/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:ManagementSegmentValue"/>
                  </tns:ManagementSegmentValue>
               </xsl:if>
               <xsl:if test="ns0:OriginatingBalSegValue">
                  <tns:OriginatingBalSegValue>
                     <xsl:if test="ns0:OriginatingBalSegValue/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:OriginatingBalSegValue/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:OriginatingBalSegValue"/>
                  </tns:OriginatingBalSegValue>
               </xsl:if>
               <xsl:if test="ns0:SetOfBooksId">
                  <tns:SetOfBooksId>
                     <xsl:if test="ns0:SetOfBooksId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:SetOfBooksId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:SetOfBooksId"/>
                  </tns:SetOfBooksId>
               </xsl:if>
               <xsl:if test="ns0:TaxCode">
                  <tns:TaxCode>
                     <xsl:if test="ns0:TaxCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TaxCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TaxCode"/>
                  </tns:TaxCode>
               </xsl:if>
               <xsl:if test="ns0:TransactionDate">
                  <tns:TransactionDate>
                     <xsl:if test="ns0:TransactionDate/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:TransactionDate/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:TransactionDate"/>
                  </tns:TransactionDate>
               </xsl:if>
               <xsl:if test="ns0:USSGLTransactionCode">
                  <tns:USSGLTransactionCode>
                     <xsl:if test="ns0:USSGLTransactionCode/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:USSGLTransactionCode/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:USSGLTransactionCode"/>
                  </tns:USSGLTransactionCode>
               </xsl:if>
               <xsl:if test="ns0:GlInterfaceId">
                  <tns:GlInterfaceId>
                     <xsl:if test="ns0:GlInterfaceId/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:GlInterfaceId/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:GlInterfaceId"/>
                  </tns:GlInterfaceId>
               </xsl:if>
               <xsl:if test="ns0:LegalEntityIdentifier">
                  <tns:LegalEntityIdentifier>
                     <xsl:if test="ns0:LegalEntityIdentifier/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:LegalEntityIdentifier/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:LegalEntityIdentifier"/>
                  </tns:LegalEntityIdentifier>
               </xsl:if>
               <xsl:if test="ns0:LedgerName">
                  <tns:LedgerName>
                     <xsl:if test="ns0:LedgerName/@xsi:nil">
                        <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                           <xsl:value-of select="ns0:LedgerName/@xsi:nil"/>
                        </xsl:attribute>
                     </xsl:if>
                     <xsl:value-of select="ns0:LedgerName"/>
                  </tns:LedgerName>
               </xsl:if>
            </tns:GlInterface>
         </xsl:for-each>
      </tns:CrearACRequest>
   </xsl:template>
</xsl:stylesheet>
