<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ErpIntegrationService"
     targetNamespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ERPIntegrationService">
        <plnk:role name="ErpIntegrationService" portType="tns:ErpIntegrationService"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/apps/financials/commonModules/shared/model/erpIntegrationService/"
         location="https://eggx.fs.us6.oraclecloud.com:443/fscmService/ErpIntegrationService?wsdl"/>
</wsdl:definitions>
